CREATE TABLE [DB].[DatabaseInfo] (
    [ServerName]                                  NVARCHAR (128)  NOT NULL,
    [InstanceName]                                NVARCHAR (128)  NOT NULL,
    [DBName]                                      NVARCHAR (128)  NULL,
    [DBStatus]                                    NVARCHAR (20)   NULL,
    [DBOwner]                                     NVARCHAR (128)  NULL,
    [DBCreateDate]                                SMALLDATETIME   NULL,
    [DBSizeInMB]                                  DECIMAL (10, 2) NULL,
    [DBSpaceAvailableInMB]                        DECIMAL (10, 2) NULL,
    [DBUsedSpaceInMB]                             DECIMAL (10, 2) NULL,
    [DBPctFreeSpace]                              NVARCHAR (10)   NULL,
    [DBDataSpaceUsageInMB]                        DECIMAL (10, 2) NULL,
    [DBIndexSpaceUsageInMB]                       DECIMAL (10, 2) NULL,
    [ActiveConnections]                           INT             NULL,
    [Collation]                                   NVARCHAR (30)   NULL,
    [RecoveryModel]                               NVARCHAR (10)   NULL,
    [CompatibilityLevel]                          NVARCHAR (30)   NULL,
    [PrimaryFilePath]                             NVARCHAR (256)  NULL,
    [LastBackupDate]                              NVARCHAR (128)  NULL,
    [LastDifferentialBackupDate]                  NVARCHAR (128)  NULL,
    [LastLogBackupDate]                           NVARCHAR (128)  NULL,
    [AutoShrink]                                  BIT             NULL,
    [AutoUpdateStatisticsEnabled]                 BIT             NULL,
    [IsReadCommittedSnapshotOn]                   BIT             NULL,
    [IsFullTextEnabled]                           BIT             NULL,
    [BrokerEnabled]                               BIT             NULL,
    [ReadOnly]                                    BIT             NULL,
    [EncryptionEnabled]                           BIT             NULL,
    [IsDatabaseSnapshot]                          BIT             NULL,
    [ChangeTrackingEnabled]                       BIT             NULL,
    [IsMirroringEnabled]                          BIT             NULL,
    [MirroringPartnerInstance]                    NVARCHAR (128)  NULL,
    [MirroringStatus]                             NVARCHAR (30)   NULL,
    [MirroringSafetyLevel]                        NVARCHAR (30)   NULL,
    [ReplicationOptions]                          NVARCHAR (30)   NULL,
    [AvailabilityGroupName]                       NVARCHAR (128)  NULL,
    [NoOfTbls]                                    INT             NULL,
    [NoOfViews]                                   SMALLINT        NULL,
    [NoOfStoredProcs]                             SMALLINT        NULL,
    [NoOfUDFs]                                    SMALLINT        NULL,
    [NoOfLogFiles]                                TINYINT         NULL,
    [NoOfFileGroups]                              TINYINT         NULL,
    [NoOfUsers]                                   SMALLINT        NULL,
    [NoOfDBTriggers]                              TINYINT         NULL,
    [LastGoodDBCCCheckDB]                         NVARCHAR (128)  NULL,
    [AutoClose]                                   BIT             NULL,
    [HasFileInCloud]                              BIT             NULL,
    [HasMemoryOptimizedObjects]                   BIT             NULL,
    [MemoryAllocatedToMemoryOptimizedObjectsInKB] DECIMAL (20, 2) NULL,
    [MemoryUsedByMemoryOptimizedObjectsInKB]      DECIMAL (20, 2) NULL,
    [DateAdded]                                   SMALLDATETIME   NULL,
    [DBID]                                        INT             IDENTITY (1, 1) NOT NULL
);


GO
CREATE CLUSTERED INDEX [CI_DatabaseInfo]
    ON [DB].[DatabaseInfo]([InstanceName] ASC, [DBName] ASC, [DateAdded] ASC, [DBID] ASC) WITH (FILLFACTOR = 85);

