CREATE TABLE [Inst].[SQLServerVersion] (
    [ID]                  INT             IDENTITY (1, 1) NOT NULL,
    [SQLVersion]          NVARCHAR (128)  NOT NULL,
    [SQLVersionNo]        NVARCHAR (128)  NOT NULL,
    [ServicePack]         NVARCHAR (128)  NULL,
    [ServicePackURL]      NVARCHAR (500)  NULL,
    [CumulativeUpdate]    NVARCHAR (128)  NULL,
    [CumulativeUpdateURL] NVARCHAR (500)  NULL,
    [Description]         NVARCHAR (2000) NULL,
    [ReleaseDate]         DATE            NULL,
    [SupportEnds]         DATE            NULL,
    [SupportLevel]        NVARCHAR (128)  NOT NULL,
    [URL]                 NVARCHAR (MAX)  NULL,
    [FileName]            NVARCHAR (255)  NULL,
    [FilePath]            NVARCHAR (2000) NULL,
    [VersionSignOffUser]  NVARCHAR (128)  NULL,
    [MGTCR]               NVARCHAR (50)   NULL,
    [DEVCR]               NVARCHAR (50)   NULL,
    [SITCR]               NVARCHAR (50)   NULL,
    [UATCR]               NVARCHAR (50)   NULL,
    [TRNCR]               NVARCHAR (50)   NULL,
    [HFXCR]               NVARCHAR (50)   NULL,
    [PRDCR]               NVARCHAR (50)   NULL,
    [MGTApprovedDate]     DATETIME2 (7)   NULL,
    [DEVApprovedDate]     DATETIME2 (7)   NULL,
    [SITApprovedDate]     DATETIME2 (7)   NULL,
    [UATApprovedDate]     DATETIME2 (7)   NULL,
    [TRNApprovedDate]     DATETIME2 (7)   NULL,
    [HFXApprovedDate]     DATETIME2 (7)   NULL,
    [PRDApprovedDate]     DATETIME2 (7)   NULL,
    [DateAdded]           DATETIME2 (7)   CONSTRAINT [DF_SQLServerVersion_DateAdded] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_SQLServerVersion_ID] UNIQUE NONCLUSTERED ([ID] ASC)
);

