CREATE TABLE [FRK].[BlitzCache] (
    [ID]                            BIGINT             IDENTITY (1, 1) NOT NULL,
    [ServerName]                    NVARCHAR (256)     NULL,
    [CheckDate]                     DATETIMEOFFSET (7) NULL,
    [Version]                       NVARCHAR (256)     NULL,
    [QueryType]                     NVARCHAR (256)     NULL,
    [Warnings]                      VARCHAR (MAX)      NULL,
    [DatabaseName]                  [sysname]          NOT NULL,
    [SerialDesiredMemory]           FLOAT (53)         NULL,
    [SerialRequiredMemory]          FLOAT (53)         NULL,
    [AverageCPU]                    BIGINT             NULL,
    [TotalCPU]                      BIGINT             NULL,
    [PercentCPUByType]              MONEY              NULL,
    [CPUWeight]                     MONEY              NULL,
    [AverageDuration]               BIGINT             NULL,
    [TotalDuration]                 BIGINT             NULL,
    [DurationWeight]                MONEY              NULL,
    [PercentDurationByType]         MONEY              NULL,
    [AverageReads]                  BIGINT             NULL,
    [TotalReads]                    BIGINT             NULL,
    [ReadWeight]                    MONEY              NULL,
    [PercentReadsByType]            MONEY              NULL,
    [AverageWrites]                 BIGINT             NULL,
    [TotalWrites]                   BIGINT             NULL,
    [WriteWeight]                   MONEY              NULL,
    [PercentWritesByType]           MONEY              NULL,
    [ExecutionCount]                BIGINT             NULL,
    [ExecutionWeight]               MONEY              NULL,
    [PercentExecutionsByType]       MONEY              NULL,
    [ExecutionsPerMinute]           MONEY              NULL,
    [PlanCreationTime]              DATETIME           NULL,
    [PlanCreationTimeHours]         INT                NULL,
    [LastExecutionTime]             DATETIME           NULL,
    [PlanHandle]                    VARBINARY (64)     NULL,
    [Remove Plan Handle From Cache] VARCHAR (MAX)      NULL,
    [SqlHandle]                     VARBINARY (64)     NULL,
    [Remove SQL Handle From Cache]  VARCHAR (MAX)      NULL,
    [SQL Handle More Info]          VARCHAR (MAX)      NULL,
    [QueryHash]                     BINARY (8)         NULL,
    [Query Hash More Info]          VARCHAR (MAX)      NULL,
    [QueryPlanHash]                 BINARY (8)         NULL,
    [StatementStartOffset]          INT                NULL,
    [StatementEndOffset]            INT                NULL,
    [MinReturnedRows]               BIGINT             NULL,
    [MaxReturnedRows]               BIGINT             NULL,
    [AverageReturnedRows]           MONEY              NULL,
    [TotalReturnedRows]             BIGINT             NULL,
    [QueryText]                     NVARCHAR (MAX)     NULL,
    [QueryPlan]                     XML                NULL,
    [NumberOfPlans]                 INT                NULL,
    [NumberOfDistinctPlans]         INT                NULL,
    [MinGrantKB]                    BIGINT             NULL,
    [MaxGrantKB]                    BIGINT             NULL,
    [MinUsedGrantKB]                BIGINT             NULL,
    [MaxUsedGrantKB]                BIGINT             NULL,
    [PercentMemoryGrantUsed]        MONEY              NULL,
    [AvgMaxMemoryGrant]             MONEY              NULL,
    [QueryPlanCost]                 FLOAT (53)         NULL,
    CONSTRAINT [PK_BlitzCache] PRIMARY KEY CLUSTERED ([ID] ASC)
);

